name: phase-engineered-symmetries
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - qutip>=5.0
  - sympy>=1.12
  - numpy>=1.24
  - matplotlib>=3.7
  - cmcrameri>=1.8
  - pip
  - pip:
    - cmap>=1.0